appconfig/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apps.login.urls')),
    path('inicio/', include('apps.inicio.urls')),
    path('dashboard/', include('apps.dashboard.urls')),
    path('productos/', include('apps.productos.urls',namespace="productos")),
    path('rangos/', include('apps.rangos.urls', namespace="rangos")),
]

apps/productos/urls.py
from django.urls import path
from . import views
from django.contrib.auth.decorators import login_required
from django.conf import settings 
from django.conf.urls.static import static

app_name = 'productos'

urlpatterns = [
    path('', login_required(views.inicio), name='index'),
    path('list/', login_required(views.ProductoList.as_view()), name='list_productos'), 
    path('create/', login_required(views.ProductoCreate.as_view()), name='create_productos'),
    path('update/<int:pk>/', login_required(views.ProductoUpdate.as_view()), name='update_productos'),
    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/rangos/urls.py
from django.urls import path
from . import views
from django.contrib.auth.decorators import login_required
from django.conf import settings 
from django.conf.urls.static import static

app_name = 'rangos'

urlpatterns = [
    path('', login_required(views.Rangos), name='index'),
     path('list/', login_required(views.RangosList.as_view()), name='list_productos'), 
]

apps/rangos/models.py
from django.db import models
from apps.productos.models import Productos
# Create your models here.

class Rangos (models.Model):

    nombre = models.CharField(max_length=100)
    codigo = models.CharField(max_length=15)
    is_active = models.BooleanField(default="true")

    def __str__(self):
        #producto = (self.pk +'('+ self.nombre+')')
        return self.nombre


    
class Rango_productos (models.Model):

    rango_id    = models.ForeignKey(Rangos, on_delete=models.CASCADE, null=False, blank=False)
    producto_id = models.ForeignKey(Productos, on_delete=models.CASCADE, null=False, blank=False)
    created_at  = models.DateTimeField(auto_now_add=True)

apps/rangos/views.py
from itertools import product
from urllib import request
from django.shortcuts import render, redirect 
from django.views.generic import ListView, CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy
from django.core.serializers import serialize
from django.http import HttpResponse, JsonResponse
from django.db import connection
from funtions import dictfetchall
import json

#Search model y forms

from .models import Rango_productos, Rangos

# Create your views here.
def Rangos(request):
    return render(request, 'rangos/index.html')

############## SEARCH PRODUCTS ##############

class RangosList(ListView):
 
    template_name = "rangos/index.html"

    def post(self, request, *args, **kwargs):
        
        if request.method == "POST":
            cursor = connection.cursor()
            cursor.execute('SELECT id, nombre, codigo FROM dbemploytel.rangos_rangos;')
            rows = dictfetchall(cursor)
            return JsonResponse(rows, safe=False)
        else:
            mensajes = f'{self.model.__name__} no se pudo registrar!'
            status_code = 401
            return JsonResponse({'mensajes': mensajes, 'status': status_code})

templates/rangos/index.html
{% extends "layouts/basedas.html" %}
{% load static %}
{% block content %}
    <!-- Content Header (Page header)-->
    <div class="content-header">
        <div class="container-fluid">
        </div><!-- /.container-fluid-->
    </div>
    <!-- Main content -->
    <section class="content">
        <div class="container-fluid">
            <!-- List Empresas -->
            <div class="row">
                <div class="col-12">
                    <div class="card card-default border-top border-primary">
                        <div class="card-header ">
                            <div class="col-12 d-flex justify-content-between align-items-center">
                                <h5 class="m-0 text-dark"><i class="fas fa-store"></i>&nbsp; Listado de Rangos</h5>
                                <button type="submit"  class="btn btn-success btn-circle" title="Registrar Producto" onclick="abrir_modal('{% url 'productos:create_productos' %}', '#productosNew')"><i class="fa-solid fa-plus fa-lg"></i></button>
                            </div>
                        </div>
                        <div class="card-body">
                            {% csrf_token %}
                            <table id="table_rangos" class="table table-striped table-bordered table-hover responsive" style="font-size: 14px; font: sans-serif; text-align: center;" cellspacing="0" width="100%">
                                <thead>
                                    <tr>
                                        <th class="text-center" width="2%">#</th>
                                        <th class="text-center">Acci&oacute;n</th>
                                        <th class="text-center">Nombre</th>
                                        <th class="text-center">C&oacute;digo</th>
                                    </tr>
                                </thead>
                                <tbody style="text-align: center;"></tbody>
                            </table>   
                        </div>
                    </div>
                </div>
            </div>
            <!-- Modal Sucursales -->   
            <div class="row">
                <!-- Modal -->
                <div class="modal fade" id="productosNew" tabindex="-1" role="dialog" aria-hidden="true"></div>
                <div class="modal fade" id="productosEdit" tabindex="-1" role="dialog" aria-hidden="true"></div>
            </div>
        </div>
    </section>
    {% block extrajs %}
    <script src="{% static '/js/reqs/rangos/index.js' %}"></script>
    {% endblock extrajs %}

{% endblock content %}