appconfig/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apps.login.urls')),
    path('inicio/', include('apps.inicio.urls')),
    path('dashboard/', include('apps.dashboard.urls')),
    path('productos/', include('apps.productos.urls',namespace="productos")),
    path('rangos/', include('apps.rangos.urls', namespace="rangos")),
]

apps/login/urls.py
from unicodedata import name
from django.urls import path
from . import views

app_name = 'login'


urlpatterns = [

    path('', views.index, name='index'),
    path('acceso/', views.acceso, name='acceso'),
    path('logout/', views.logout, name='logout'),
    
]

templates/layouts/base.html
{% load static sitetree %}
<!DOCTYPE html>
<html lang="en">
    <head>

        <meta charset="UTF-8">
        <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
        <title>EMPLOYEE BENEFIT PROGRAM | SEBP </title>
        <!-- Favicon icon -->
        <link rel="icon" type="image/png" sizes="36x36" href="{% static '/images/telefonica/TelefonicaLogo.png' %}">

        <!--############################################### STYLES CSS ########################################-->
        <!-- Font Awesome -->
        <link href="{% static 'vendor/fontawesome6/css/all.min.css' %}" rel="stylesheet" type="text/css">
        <!-- Bootstrap Core Css -->
        <link rel="stylesheet" href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}">
        <!-- Toastr -->
        <link rel="stylesheet" href="{% static 'vendor/toastr/toastr.min.css' %}">
        <!-- Datatables Css -->
        <link rel="stylesheet" href="{% static 'vendor/datatables/dataTables.min.css' %}">
        <link rel="stylesheet" href="{% static 'vendor/datatables/AutoFill/css/autoFill.dataTables.min.css' %}">
        <link rel="stylesheet" href="{% static 'vendor/datatables/Buttons/css/buttons.dataTables.min.css' %}">
        <link rel="stylesheet" href="{% static 'vendor/datatables/Responsive/css/responsive.bootstrap5.min.css' %}">
        <link rel="stylesheet" href="{% static 'vendor/datatables/Scroller/css/scroller.dataTables.min.css' %}">
        <link rel="stylesheet" href="{% static 'vendor/datatables/Select/css/select.dataTables.min.css' %}">
        <!-- Styles Generals -->
        <link rel="stylesheet" href="{% static 'css/app.css' %}">
        <link rel="stylesheet" href="{% static 'css/generalstyle.css' %}">
    </head>
    <body>
        <!-- ##################### NAVBAR ##################### -->
        
        <nav class="navbar navbar-expand-lg bg-primary">
            <div class="container-fluid " >
                <a class="navbar-brand" href="#">
                    <img src="{% static 'images/favicon/movistar_white.png' %}" height="20%">
                </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0"></ul>
                    <div class="d-flex">
                        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                    <i class="fa-solid fa-circle-user text-white"></i> 
                                    <span class="text-white"><b>{{codem}} - </b></span>
                                    <span class="text-white"><b>{{fullName}}</b></span>
                                </a>
                                <ul class="dropdown-menu">
                                    <li>
                                        <a class="dropdown-item" href="{% url 'login:logout' %}"> <i class="fa-solid fa-right-from-bracket"></i> &nbsp; Salir</a>
                                    </li>
                                </ul>
                            </li>                      
                        </ul>
                    </div>
                </div>
            </div>
        </nav>
        <!-- Content Wrapper. Contains page content -->
        <div class="content-wrapper">
            {% block content %}
        
            {% endblock %}
        </div>
        <!-- ##################### JAVASCRIPT ##################### -->
        <!-- jQuery -->
        <script type="text/javascript" src="{% static 'vendor/jquery/jquery3.6.0.min.js' %}"></script>
        <!-- Font Awesome -->
        <link href="{% static 'vendor/fontawesome6/js/all.min.js' %}" rel="stylesheet" type="text/css">
        <!-- Bootstrap Core Js -->
        <script type="text/javascript" src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
        <script type="text/javascript" src="{% static 'vendor/popper/popper.min.js' %}"></script>
        <!-- Toastr -->
        <script type="text/javascript" src="{% static 'vendor/toastr/toastr.min.js' %}"></script>
        <!-- Sweetalert 2 Js -->
        <script type="text/javascript" src="{% static 'vendor/sweetalert/sweetalert2.min.js' %}"></script>
        <!-- Datatables JS -->
        <script type="text/javascript" src="{% static 'vendor/datatables/datatables.min.js' %}"></script>
        <script type="text/javascript" src="{% static 'vendor/datatables/AutoFill/js/autoFill.dataTables.min.js' %}"></script>
        <script type="text/javascript" src="{% static 'vendor/datatables/Buttons/js/buttons.dataTables.min.js' %}"></script>
        <script type="text/javascript" src="{% static 'vendor/datatables/Buttons/js/buttons.html5.min.js' %}"></script>
        <script type="text/javascript" src="{% static 'vendor/datatables/Buttons/js/buttons.print.min.js' %}"></script>
        <script type="text/javascript" src="{% static 'vendor/datatables/JSZip/jszip.min.js' %}"></script>
        <script type="text/javascript" src="{% static 'vendor/datatables/pdfmake/pdfmake.min.js' %}"></script>
        <script type="text/javascript" src="{% static 'vendor/datatables/pdfmake/vfs_fonts.js' %}"></script>
        <script type="text/javascript" src="{% static 'vendor/datatables/Responsive/js/responsive.bootstrap5.min.js' %}"></script>
        <script type="text/javascript" src="{% static 'vendor/datatables/Scroller/js/scroller.dataTables.min.js' %}"></script>
        <script type="text/javascript" src="{% static 'vendor/datatables/Select/js/select.dataTables.min.js' %}"></script>
        <!-- Datepicker  Js -->
        <script type="text/javascript" src="{% static 'vendor/datepicker/js/bootstrap-datepicker.min.js' %}"></script>
        <!-- Validaciones Custom -->
        <script type="text/javascript" src="{% static 'js/custom/validaciones.js' %}"></script>
    
    </body>
</html>

templates/layouts/basedas.html
{% load static sitetree %}
<!DOCTYPE html>
<html lang="en">

    <head>

        <meta charset="UTF-8">
        <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
        <title>EMPLOYEE BENEFIT PROGRAM | SEBP </title>
        <!-- Favicon icon -->
        <link rel="icon" type="image/png" sizes="36x36" href="{% static '/images/telefonica/TelefonicaLogo.png' %}">
        <!--############################################### STYLES CSS #######################################################-->
        <!-- Font Awesome -->
        <link href="{% static 'vendor/fontawesome6/css/all.min.css' %}" rel="stylesheet" type="text/css">
        <!-- Bootstrap Core Css -->
        <link rel="stylesheet" href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}">
        <!-- AdminLte -->
        <link rel="stylesheet" href="{% static 'vendor/adminlte/css/adminlte.min.css' %}">
        <!-- Menu Principal -->
        <link rel="stylesheet" href="{% static 'css/menu.css' %}">
        <!-- Toastr -->
        <link rel="stylesheet" href="{% static 'vendor/toastr/toastr.min.css' %}">
        <!-- Style Principal -->
        <link rel="stylesheet" href="{% static 'css/generalstyle.css' %}">
        <!-- Datatables Css -->
        <link rel="stylesheet" href="{% static 'vendor/datatables/dataTables.min.css' %}">
        <link rel="stylesheet" href="{% static 'vendor/datatables/AutoFill/css/autoFill.dataTables.min.css' %}">
        <link rel="stylesheet" href="{% static 'vendor/datatables/Buttons/css/buttons.dataTables.min.css' %}">
        <link rel="stylesheet" href="{% static 'vendor/datatables/Responsive/css/responsive.dataTables.min.css' %}">
        <link rel="stylesheet" href="{% static 'vendor/datatables/Scroller/css/scroller.dataTables.min.css' %}">

    </head>
    <body class="hold-transition sidebar-mini">
        <div class="wrapper">
            <nav class="main-header navbar navbar-expand navbar-white navbar-light">
                <!-- Left navbar links -->
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link" data-widget="pushmenu" href="#"><i class="fas fa-bars"></i></a>
                    </li>
                </ul>
                <!-- Right navbar links -->
                <ul class="navbar-nav ml-auto">
                    <li class="nav-item">
                        <a class="nav-link" data-widget="navbar-search" href="#" role="button">
                            <img src="{% static 'images/profile-img.jpg' %}" class="img-size-32 mr-3 img-circle" alt="User Image">
                            <b>{{request.user.first_name}} {{ request.user.last_name }}</b>
                        </a>
                    </li>
                </ul>
            </nav>
            <!-- Main Sidebar Container -->
            <aside class="main-sidebar sidebar-dark-primary  elevation-4">
                <!-- Brand Logo -->
                <a href="#" class="brand-link">
                    <img src="{% static 'images/telefonica/TelefonicaLogoWhite.png' %}" alt="SOFTCOMD"
                            class="brand-image img-circle elevation-3">
                    <span class="brand-text font-weight-light"><b>SEBP</b></span>
                </a>
                <!-- Sidebar -->
                <div class="sidebar">
                    <!-- Sidebar user panel (optional) -->
                    <!-- Menu -->
                    <nav class="mt-2">
                        {% sitetree_menu from "mainmenu" include "trunk" template "main/index.html" %}
                    </nav> 
                </div>
            </aside>
            <!-- Content Wrapper. Contains page content -->
            <div class="content-wrapper">
                {% block content %}

                {% endblock %}
            </div>
            <!-- MAIN FOOTER-->
            <footer class="main-footer">
                <strong>Copyright &copy; 
                    <script>
                    document.write(new Date().getFullYear())
                    </script>, <a href="#">AUTODIG</a>.</strong> All rights reserved.
                <div class="float-right d-none d-sm-inline-block">
                    <b>Version</b> 1.0.0
                </div>
            </footer>
        </div>

        <!-- jQuery -->
        <script type="text/javascript" src="{% static 'vendor/jquery/jquery3.6.0.min.js' %}"></script>
        <!-- Font Awesome -->
        <link href="{% static 'vendor/fontawesome6/js/all.min.js' %}" rel="stylesheet" type="text/css">
        <!-- Bootstrap Core Js -->
        <script type="text/javascript" src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
        <script type="text/javascript" src="{% static 'vendor/popper/popper.min.js' %}"></script>
        <!-- AdminLTE App -->
        <script type="text/javascript" src="{% static 'vendor/adminlte/js/adminlte.min.js' %}"></script>
        <!-- Toastr -->
        <script type="text/javascript" src="{% static 'vendor/toastr/toastr.min.js' %}"></script>
        <!-- Sweetalert 2 Js -->
        <script type="text/javascript" src="{% static 'vendor/sweetalert/sweetalert2.min.js' %}"></script>
        <!-- Datatables JS -->
        <script type="text/javascript" src="{% static 'vendor/datatables/datatables.min.js' %}"></script>
        <script type="text/javascript" src="{% static 'vendor/datatables/AutoFill/js/autoFill.dataTables.min.js' %}"></script>
        <script type="text/javascript" src="{% static 'vendor/datatables/Buttons/js/buttons.dataTables.min.js' %}"></script>
        <script type="text/javascript" src="{% static 'vendor/datatables/Buttons/js/buttons.html5.min.js' %}"></script>
        <script type="text/javascript" src="{% static 'vendor/datatables/Buttons/js/buttons.print.min.js' %}"></script>
        <script type="text/javascript" src="{% static 'vendor/datatables/JSZip/jszip.min.js' %}"></script>
        <script type="text/javascript" src="{% static 'vendor/datatables/pdfmake/pdfmake.min.js' %}"></script>
        <script type="text/javascript" src="{% static 'vendor/datatables/pdfmake/vfs_fonts.js' %}"></script>
        <script type="text/javascript" src="{% static 'vendor/datatables/Responsive/js/dataTables.responsive.min.js' %}"></script>
        <script type="text/javascript" src="{% static 'vendor/datatables/Scroller/js/scroller.dataTables.min.js' %}"></script>
        <!-- Datepicker  Js -->
        <script type="text/javascript" src="{% static 'vendor/datepicker/js/bootstrap-datepicker.min.js' %}"></script>
        <!-- Validaciones Custom -->
        <script type="text/javascript" src="{% static 'js/custom/validaciones.js' %}"></script>
    </body>

templates/layouts/baselogin.html
{% load static sitetree %}
<!DOCTYPE html>
<html lang="en">

   	<head>
    	<meta charset="UTF-8">
        <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    	<title>SYSTEMS EMPLOYEE BENEFIT PROGRAM | SEBP </title>
        <!-- Favicon icon -->
        <link rel="icon" type="image/png" sizes="36x36" href="{% static '/images/telefonica/TelefonicaLogo.png' %}">

    <!--############################################### STYLES CSS #######################################################-->
        <!-- MDB CLI -->
        <link rel="stylesheet" href="{% static 'vendor/mdb5/css/mdb.min.css' %}" rel="stylesheet">
        <!--     Fonts and icons     -->
        <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700" rel="stylesheet" />
        <!-- Font Awesome Icons -->
        <script src="https://kit.fontawesome.com/42d5adcbca.js" crossorigin="anonymous"></script>
        <link href="{% static 'css/login/nucleo-svg.css' %}" rel="stylesheet" />
        <link href="{% static 'css/login/soft-ui-dashboard.css' %}" id="pagestyle" rel="stylesheet" />
        <link href="{% static 'vendor/toastr/toastr.min.css' %}" rel="stylesheet" >
        
        <script type="text/javascript" src="{% static 'vendor/sweetalert/sweetalert2.min.js' %}"></script>
        <script type="text/javascript" src="{% static 'js/custom/validaciones.js' %}"></script>
    </head>
    <body>
        
        {% block content %}
        
        {% endblock %}

        <!--   Core JS Files   -->
        <script type="text/javascript" src="{% static 'vendor/jquery/jquery3.6.0.min.js' %}"></script>
        <script type="text/javascript" src="{% static 'vendor/popper/popper.min.js' %}"></script>
        <!-- MDB CLI -->
        <script type="text/javascript" src="{% static 'vendor/mdb5/js/mdb.min.js' %}"></script>
        <script type="text/javascript" src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
        <script type="text/javascript" src="{% static '/js/login/plugins/perfect-scrollbar.min.js' %}"></script>
        <script type="text/javascript" src="{% static '/js/login/plugins/smooth-scrollbar.min.js' %}"></script>
        <script type="text/javascript" src="{% static 'vendor/toastr/toastr.min.js' %}"></script>
        <script src="{% static '/js/login/soft-ui-dashboard.min.js' %}"></script>
    </body>