appconfig/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apps.login.urls')),
    path('inicio/', include('apps.inicio.urls')),
    path('dashboard/', include('apps.dashboard.urls')),
    path('productos/', include('apps.productos.urls',namespace="productos")),
    path('rangos/', include('apps.rangos.urls', namespace="rangos")),
]

apps/login/urls.py
from unicodedata import name
from django.urls import path
from . import views

app_name = 'login'


urlpatterns = [

    path('', views.index, name='index'),
    path('acceso/', views.acceso, name='acceso'),
    path('logout/', views.logout, name='logout'),
    
]

apps/login/models.py
from django.contrib.auth.models import AbstractUser, BaseUserManager
from django.db import models
from django.utils.translation import gettext_lazy as _

# Create your models here.

class UserManager(BaseUserManager):

    def _create_user(self, email, password, **extra_fields):

        if not email:
            raise ValueError('El correo debe estar activo')
        email = self.normalize_email(email)
        user  = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user
    
    def create_user(self, email, password=None, **extra_fields):

        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)

        if extra_fields.get('is_staff') is not True:
            raise ValueError('El superusuario debe tener is_staff = True.')
        if extra_fields.get('is_superuser') is not True:
            raise ValueError('El superusuario debe tener is_superuser = True.')

        return self._create_user(email, password, **extra_fields)
    
    def create_superuser(self, email, password, **extra_fields):
        """Create and save a SuperUser with the given email and password."""
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)

        if extra_fields.get('is_staff') is not True:
            raise ValueError('El superusuario debe tener is_staff=True.')
        if extra_fields.get('is_superuser') is not True:
            raise ValueError('El superusuario debe tener is_superuser=True.')

        return self._create_user(email, password, **extra_fields)

class User (AbstractUser):

    """USER MODEL."""

    username = None
    email = models.EmailField(_('email address'), unique=True)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    objects = UserManager()

apps/login/views.py
from django.shortcuts import render, redirect 
from django.http import HttpResponse, JsonResponse
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import authenticate, login as do_login, logout as do_logout

from django.contrib import messages
from ldap3.core.exceptions import LDAPException, LDAPBindError
from django.conf import settings
from django.core.cache import cache
from ldap3 import Server, Connection, NTLM, SUBTREE
from django.db import connection
from funtions import dictfetchall
import json

from apps.inicio.models import Accounts

# Create your views here.

def index(request):
    return render(request, 'login/index.html')

def acceso(request):
    
    if request.method == 'POST':
    
        ## DATOS DEL CLIENTE O USUARIO  ##
        username = request.POST['username'].lower()
        password = request.POST['password']
        useremail = request.POST['useremail']

        if(useremail):

            user = authenticate(username=useremail, password=password)
            if user:
                if user.is_active:
                    do_login(request, user)
                    return redirect('/dashboard/')
            else:
                messages.add_message(request, messages.ERROR, 'La combinación de correo/contraseña son incorrectos. Inténtalo de nuevo.!')
                return render (request, 'login/index.html')
        else:

            ## DATOS DEL SERVICIO ## 
            server_uri = Server(settings.AD_HOST)
            damain_uri = settings.AD_DOMAIN_NAME
            user_uri = user="{0}\\{1}".format(damain_uri, username)

            ## DATOS DE LA CONEXION ##
            conn = Connection(server_uri, user_uri, password=password, authentication=NTLM)
            conn.start_tls()
            bind_response = conn.bind()
            if bind_response:
                qryset = searchusrDat(username)
                if qryset[0]['compro'] == 0:
                    data = {
                        'id': qryset[0]['id'],
                        'cedula': qryset[0]['cedula'],
                        'nombre': qryset[0]['nombre'],
                        'codemo': qryset[0]['codempleado'],
                        'rangod': qryset[0]['rango_id']
                    }
                    info = request.session['info'] = data
                    return redirect('/inicio/', {"info":info})
                else:
                    messages.add_message(request, messages.INFO, 'Usuario realizo un comprar. Comuniquese con Gestión Humana.!')
                    return render (request, 'login/index.html')
            else:
                messages.add_message(request, messages.ERROR, 'La combinación de correo/contraseña son incorrectos. Inténtalo de nuevo.!')
                return render (request, 'login/index.html')
    else:
        return redirect('/')


def searchusrDat(usr):
        
        cursor = connection.cursor()
        cursor.execute('SELECT id, cedula, nombre, codempleado, compro, rango_id FROM dbemploytel.viewempleados where codempleado =%s', [usr])
        rows = dictfetchall(cursor)
        cursor.close()
        return rows

def logout(request):
    # Redireccionamos a la portada
    return redirect('/')

templates/login/index.html
{% extends 'layouts/baselogin.html' %}
{% load static  %}
{% block content %}
    <main class="main-content mt-0">
        <section>
            <div class="page-header min-vh-100">
                <div class="container">         
                    <div class="position-absolute top-0 start-3 text-left my-5 ">
                        <img src="{% static '/images/telefonica/TelefonicaLogo.png' %}" alt="" width="80">
                        <img src="{% static '/images/telefonica/TelefonicaName.png' %}" alt="" width="100">
                    </div>          
                    <div class="row" >
                        <div class="col-xl-4 col-lg-6 col-md-6 d-flex flex-column mx-auto">
                            <!-- LOGIN -->
                            <div class="card card-plain" id="DivLogin" style="display: block;">
                                <div class="card-header pb-0 text-left bg-transparent">
                                    <p class="text-secondary text-center fs-3 display-6 ">PROGRAMA DE BENEFICIO AL EMPLEADO</p>
                                    <br>
                                    <h3 class="font-weight-bolder text-info">Bienvenido</h3>
                                    <p class="mb-0">Introduzca su c&oacute;digo de empleado y contraseña de red</p>
                                </div>
                                <div class="card-body" >
                                    <form id="formlogin" class="row g-3" method="post" action="{% url 'login:acceso' %}">
                                        {% csrf_token %}

                                        <!-- Codigo Empleado input -->
                                        <div class="form-outline mb-2" id="idop">
                                            <input  type="text" class="form-control form-control-lg text-uppercase" 
                                                    placeholder="EXXXXX" maxlength="6"
                                                    name="username" id="username" autocomplete="off"
                                            >
                                            <label class="form-label" for="username">C&oacute;digo Empleado</label>
                                        </div>
                                        <div class="form-outline mb-2" id="email" style="display: none;">
                                            <input  type="text" class="form-control form-control-lg " 
                                                    placeholder="xxxxxx@telefonica.com"
                                                    name="useremail" id="useremail" autocomplete="off"
                                            >
                                            <label class="form-label" for="useremail">Correo Electr&oacute;nico</label>
                                        </div>
                                        <!-- Password input -->
                                        <div class="form-outline mb-2">
                                            <input type="password" class="form-control form-control-lg"
                                                    placeholder="Enter contraseña"
                                                    name="password" id="password" autocomplete="off">
                                            <label class="form-label" for="password">Contraseña</label>
                                        </div>
                                        <div class="form-check">
                                            <input class="form-check-input" type="checkbox" value="" id="defaultCheck1">
                                            <label class="form-check-label" for="defaultCheck1">
                                                Acceso Administrador
                                            </label>
                                        </div>
                                        <div class="flex-sb-m w-full p-b-32">
                                            {{form.as_p}}
                                            <div class="form-group">
                                                <div id="menssage">
                                                    {% if messages %}
                                                    <ul class="messages">
                                                        {% for message in messages %}
                                                        <script>
                                                            notification('Error', '{{ message }}', 'error');
                                                        </script>
                                                        {% endfor %}
                                                    </ul>
                                                    {% endif %}
                                                </div>
                                            </div>  
                                        </div>
                                        <div class="text-center">
                                            <button type="button" class="btn bg-info w-100 mb-0 text-white" id="btologin" >Iniciar sesi&oacute;n</button>
                                        </div>
                                    </form>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="oblique position-absolute top-0 h-100 d-md-block d-none me-n8">
                                <div class="oblique-image bg-cover position-absolute fixed-top ms-auto h-100 z-index-0 ms-n6" style="background-image:url('/static/images/backgroundLoging.jpg')"></div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </main>

{% block extrajs %}<script src="{% static '/js/reqs/login/index.js' %}"></script>{% endblock extrajs %}

{% endblock %}